// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/Events.proto

package org.jboss.ddoyle.drools.serialization.demo.model.proto.v1;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.event);
    registry.add(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.event);
  }
  public interface ProtoBufEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent)
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<ProtoBufEvent> {

    /**
     * <code>required .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type type = 1;</code>
     */
    org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type getType();

    /**
     * <code>required int32 droolsIdentityPlaceholder = 2;</code>
     */
    boolean hasDroolsIdentityPlaceholder();
    /**
     * <code>required int32 droolsIdentityPlaceholder = 2;</code>
     */
    int getDroolsIdentityPlaceholder();

    /**
     * <code>required string id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 3;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required int64 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 4;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent}
   */
  public static final class ProtoBufEvent extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        ProtoBufEvent> implements
      // @@protoc_insertion_point(message_implements:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent)
      ProtoBufEventOrBuilder {
    // Use ProtoBufEvent.newBuilder() to construct.
    private ProtoBufEvent(com.google.protobuf.GeneratedMessage.ExtendableBuilder<org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoBufEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoBufEvent defaultInstance;
    public static ProtoBufEvent getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoBufEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoBufEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type value = org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              droolsIdentityPlaceholder_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              id_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.class, org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoBufEvent> PARSER =
        new com.google.protobuf.AbstractParser<ProtoBufEvent>() {
      public ProtoBufEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoBufEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBufEvent> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SimpleEvent = 1;</code>
       */
      SimpleEvent(0, 1),
      /**
       * <code>OtherEvent = 2;</code>
       */
      OtherEvent(1, 2),
      ;

      /**
       * <code>SimpleEvent = 1;</code>
       */
      public static final int SimpleEvent_VALUE = 1;
      /**
       * <code>OtherEvent = 2;</code>
       */
      public static final int OtherEvent_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return SimpleEvent;
          case 2: return OtherEvent;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type type_;
    /**
     * <code>required .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type type = 1;</code>
     */
    public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type getType() {
      return type_;
    }

    public static final int DROOLSIDENTITYPLACEHOLDER_FIELD_NUMBER = 2;
    private int droolsIdentityPlaceholder_;
    /**
     * <code>required int32 droolsIdentityPlaceholder = 2;</code>
     */
    public boolean hasDroolsIdentityPlaceholder() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 droolsIdentityPlaceholder = 2;</code>
     */
    public int getDroolsIdentityPlaceholder() {
      return droolsIdentityPlaceholder_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private java.lang.Object id_;
    /**
     * <code>required string id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string id = 3;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      type_ = org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type.SimpleEvent;
      droolsIdentityPlaceholder_ = 0;
      id_ = "";
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDroolsIdentityPlaceholder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, droolsIdentityPlaceholder_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, timestamp_);
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, droolsIdentityPlaceholder_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent)
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.class, org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Builder.class);
      }

      // Construct using org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type.SimpleEvent;
        bitField0_ = (bitField0_ & ~0x00000001);
        droolsIdentityPlaceholder_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_descriptor;
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent getDefaultInstanceForType() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.getDefaultInstance();
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent build() {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent buildPartial() {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent result = new org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.droolsIdentityPlaceholder_ = droolsIdentityPlaceholder_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent) {
          return mergeFrom((org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent other) {
        if (other == org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDroolsIdentityPlaceholder()) {
          setDroolsIdentityPlaceholder(other.getDroolsIdentityPlaceholder());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000004;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasDroolsIdentityPlaceholder()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type type_ = org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type.SimpleEvent;
      /**
       * <code>required .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type type = 1;</code>
       */
      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type getType() {
        return type_;
      }
      /**
       * <code>required .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type type = 1;</code>
       */
      public Builder setType(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent.Type.SimpleEvent;
        onChanged();
        return this;
      }

      private int droolsIdentityPlaceholder_ ;
      /**
       * <code>required int32 droolsIdentityPlaceholder = 2;</code>
       */
      public boolean hasDroolsIdentityPlaceholder() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 droolsIdentityPlaceholder = 2;</code>
       */
      public int getDroolsIdentityPlaceholder() {
        return droolsIdentityPlaceholder_;
      }
      /**
       * <code>required int32 droolsIdentityPlaceholder = 2;</code>
       */
      public Builder setDroolsIdentityPlaceholder(int value) {
        bitField0_ |= 0x00000002;
        droolsIdentityPlaceholder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 droolsIdentityPlaceholder = 2;</code>
       */
      public Builder clearDroolsIdentityPlaceholder() {
        bitField0_ = (bitField0_ & ~0x00000002);
        droolsIdentityPlaceholder_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string id = 3;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 3;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent)
    }

    static {
      defaultInstance = new ProtoBufEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent)
  }

  public interface ProtoBufSimpleEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufSimpleEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string testMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    boolean hasTestMessage();
    /**
     * <code>optional string testMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    java.lang.String getTestMessage();
    /**
     * <code>optional string testMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    com.google.protobuf.ByteString
        getTestMessageBytes();
  }
  /**
   * Protobuf type {@code org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufSimpleEvent}
   */
  public static final class ProtoBufSimpleEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufSimpleEvent)
      ProtoBufSimpleEventOrBuilder {
    // Use ProtoBufSimpleEvent.newBuilder() to construct.
    private ProtoBufSimpleEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoBufSimpleEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoBufSimpleEvent defaultInstance;
    public static ProtoBufSimpleEvent getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoBufSimpleEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoBufSimpleEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              testMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.class, org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoBufSimpleEvent> PARSER =
        new com.google.protobuf.AbstractParser<ProtoBufSimpleEvent>() {
      public ProtoBufSimpleEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoBufSimpleEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBufSimpleEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TESTMESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object testMessage_;
    /**
     * <code>optional string testMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    public boolean hasTestMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string testMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    public java.lang.String getTestMessage() {
      java.lang.Object ref = testMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          testMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string testMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTestMessageBytes() {
      java.lang.Object ref = testMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        testMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      testMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTestMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTestMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufSimpleEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufSimpleEvent)
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.class, org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.Builder.class);
      }

      // Construct using org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        testMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_descriptor;
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent getDefaultInstanceForType() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.getDefaultInstance();
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent build() {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent buildPartial() {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent result = new org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testMessage_ = testMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent) {
          return mergeFrom((org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent other) {
        if (other == org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.getDefaultInstance()) return this;
        if (other.hasTestMessage()) {
          bitField0_ |= 0x00000001;
          testMessage_ = other.testMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object testMessage_ = "";
      /**
       * <code>optional string testMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public boolean hasTestMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string testMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public java.lang.String getTestMessage() {
        java.lang.Object ref = testMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            testMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string testMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTestMessageBytes() {
        java.lang.Object ref = testMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          testMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string testMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public Builder setTestMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        testMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string testMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public Builder clearTestMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testMessage_ = getDefaultInstance().getTestMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string testMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public Builder setTestMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        testMessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufSimpleEvent)
    }

    static {
      defaultInstance = new ProtoBufSimpleEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufSimpleEvent)
    public static final int EVENT_FIELD_NUMBER = 100;
    /**
     * <code>extend .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent { ... }</code>
     *
     * <pre>
     *Tutorials say to use required field here, but newer ProtoBuf compiler doesn't allow that.
     * </pre>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent,
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent> event = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.getDefaultInstance(),
          0,
          org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.class,
          org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufSimpleEvent.getDefaultInstance());
  }

  public interface ProtoBufOtherEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufOtherEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string otherTestMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    boolean hasOtherTestMessage();
    /**
     * <code>optional string otherTestMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    java.lang.String getOtherTestMessage();
    /**
     * <code>optional string otherTestMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    com.google.protobuf.ByteString
        getOtherTestMessageBytes();
  }
  /**
   * Protobuf type {@code org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufOtherEvent}
   */
  public static final class ProtoBufOtherEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufOtherEvent)
      ProtoBufOtherEventOrBuilder {
    // Use ProtoBufOtherEvent.newBuilder() to construct.
    private ProtoBufOtherEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoBufOtherEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoBufOtherEvent defaultInstance;
    public static ProtoBufOtherEvent getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoBufOtherEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoBufOtherEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              otherTestMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.class, org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoBufOtherEvent> PARSER =
        new com.google.protobuf.AbstractParser<ProtoBufOtherEvent>() {
      public ProtoBufOtherEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoBufOtherEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoBufOtherEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OTHERTESTMESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object otherTestMessage_;
    /**
     * <code>optional string otherTestMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    public boolean hasOtherTestMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string otherTestMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    public java.lang.String getOtherTestMessage() {
      java.lang.Object ref = otherTestMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          otherTestMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string otherTestMessage = 1;</code>
     *
     * <pre>
     * These fields can use the full number range.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOtherTestMessageBytes() {
      java.lang.Object ref = otherTestMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otherTestMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      otherTestMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getOtherTestMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getOtherTestMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufOtherEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufOtherEvent)
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.class, org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.Builder.class);
      }

      // Construct using org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        otherTestMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_descriptor;
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent getDefaultInstanceForType() {
        return org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.getDefaultInstance();
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent build() {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent buildPartial() {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent result = new org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.otherTestMessage_ = otherTestMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent) {
          return mergeFrom((org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent other) {
        if (other == org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.getDefaultInstance()) return this;
        if (other.hasOtherTestMessage()) {
          bitField0_ |= 0x00000001;
          otherTestMessage_ = other.otherTestMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object otherTestMessage_ = "";
      /**
       * <code>optional string otherTestMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public boolean hasOtherTestMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string otherTestMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public java.lang.String getOtherTestMessage() {
        java.lang.Object ref = otherTestMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            otherTestMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string otherTestMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOtherTestMessageBytes() {
        java.lang.Object ref = otherTestMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          otherTestMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string otherTestMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public Builder setOtherTestMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        otherTestMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string otherTestMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public Builder clearOtherTestMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        otherTestMessage_ = getDefaultInstance().getOtherTestMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string otherTestMessage = 1;</code>
       *
       * <pre>
       * These fields can use the full number range.
       * </pre>
       */
      public Builder setOtherTestMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        otherTestMessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufOtherEvent)
    }

    static {
      defaultInstance = new ProtoBufOtherEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufOtherEvent)
    public static final int EVENT_FIELD_NUMBER = 101;
    /**
     * <code>extend .org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.ProtoBufEvent { ... }</code>
     *
     * <pre>
     *Tutorials say to use required field here, but newer ProtoBuf compiler doesn't allow that.
     * </pre>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufEvent,
        org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent> event = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.getDefaultInstance(),
          0,
          org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.class,
          org.jboss.ddoyle.drools.serialization.demo.model.proto.v1.Events.ProtoBufOtherEvent.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/resources/Events.proto\0229org.j" +
      "boss.ddoyle.drools.serialization.demo.mo" +
      "del.proto.v1\"\341\001\n\rProtoBufEvent\022[\n\004type\030\001" +
      " \002(\0162M.org.jboss.ddoyle.drools.serializa" +
      "tion.demo.model.proto.v1.ProtoBufEvent.T" +
      "ype\022!\n\031droolsIdentityPlaceholder\030\002 \002(\005\022\n" +
      "\n\002id\030\003 \002(\t\022\021\n\ttimestamp\030\004 \002(\003\"\'\n\004Type\022\017\n" +
      "\013SimpleEvent\020\001\022\016\n\nOtherEvent\020\002*\010\010d\020\200\200\200\200\002" +
      "\"\324\001\n\023ProtoBufSimpleEvent\022\023\n\013testMessage\030" +
      "\001 \001(\t2\247\001\n\005event\022H.org.jboss.ddoyle.drool",
      "s.serialization.demo.model.proto.v1.Prot" +
      "oBufEvent\030d \001(\0132N.org.jboss.ddoyle.drool" +
      "s.serialization.demo.model.proto.v1.Prot" +
      "oBufSimpleEvent\"\327\001\n\022ProtoBufOtherEvent\022\030" +
      "\n\020otherTestMessage\030\001 \001(\t2\246\001\n\005event\022H.org" +
      ".jboss.ddoyle.drools.serialization.demo." +
      "model.proto.v1.ProtoBufEvent\030e \001(\0132M.org" +
      ".jboss.ddoyle.drools.serialization.demo." +
      "model.proto.v1.ProtoBufOtherEvent"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufEvent_descriptor,
        new java.lang.String[] { "Type", "DroolsIdentityPlaceholder", "Id", "Timestamp", });
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufSimpleEvent_descriptor,
        new java.lang.String[] { "TestMessage", });
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_jboss_ddoyle_drools_serialization_demo_model_proto_v1_ProtoBufOtherEvent_descriptor,
        new java.lang.String[] { "OtherTestMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
