package org.jboss.ddoyle.drools.cep.sample;

import org.jboss.ddoyle.drools.serialization.demo.model.v1.SimpleEvent;

declare SimpleEvent
    @role( event )
    @timestamp( timestamp.getTime() )
    @expires( 2d )
end

rule "SimpleTestRule-One"
when
	$s:SimpleEvent()
then
	System.out.println("Rule One: Found simple event: " + $s);
end


rule "SimpleTestRule-Two"
when
	$s:SimpleEvent()
	not SimpleEvent(this != $s, this after [0,10s] $s)
then
	System.out.println("Rule Two: There's no event matching the following event within 10 seconds: " + $s);
end




/*
rule "SimpleTestRule"
when
	$n: Number(this  > 1000) from accumulate ($s: SimpleEvent(), count($s))	
then
	System.out.println("Found more than 1000 simple events: " + $n);
	System.out.println("Clock value is: " + kcontext.getKnowledgeRuntime().getSessionClock().getCurrentTime() + "\n");
end
*/

